import { Creator, Campaign, PricingPlan } from "./types";

export const mockCreators: Creator[] = [
  {
    id: "cr-001",
    handle: "@shermaine.sg",
    displayName: "Shermaine Tan",
    avatarUrl: "",
    bio: "Lifestyle & beauty creator in SG. Love café hopping and trying new skincare. Fluent in English & Mandarin.",
    city: "Singapore",
    languages: ["English", "Mandarin"],
    categories: ["Beauty", "Lifestyle", "F&B"],
    platforms: [
      { platform: "instagram", handle: "@shermaine.sg", followers: 125000, url: "https://instagram.com/shermaine.sg" },
      { platform: "tiktok", handle: "@shermaine.sg", followers: 85000, url: "https://tiktok.com/@shermaine.sg" },
    ],
    rateCardSGD: {
      instagramPost: 800,
      instagramReel: 1200,
      instagramStory: 300,
      tiktokVideo: 1000,
    },
    tags: ["Beauty", "Skincare", "Café", "Lifestyle"],
    verified: true,
    completedCampaigns: 42,
    averageRating: 4.9,
    joinedDate: "2024-08-15",
  },
  {
    id: "cr-002",
    handle: "@marcustan_eats",
    displayName: "Marcus Tan",
    avatarUrl: "",
    bio: "Your friendly neighbourhood food reviewer. Hawker centres, hidden gems, and everything in between.",
    city: "Singapore",
    languages: ["English"],
    categories: ["F&B", "Travel"],
    platforms: [
      { platform: "instagram", handle: "@marcustan_eats", followers: 180000, url: "https://instagram.com/marcustan_eats" },
      { platform: "tiktok", handle: "@marcustan_eats", followers: 220000, url: "https://tiktok.com/@marcustan_eats" },
      { platform: "youtube", handle: "Marcus Eats", followers: 45000, url: "https://youtube.com/@marcuseats" },
    ],
    rateCardSGD: {
      instagramPost: 1200,
      instagramReel: 1800,
      tiktokVideo: 1500,
      youtubeVideo: 3500,
      youtubeShort: 1200,
    },
    tags: ["Food", "Hawker", "Reviews", "Singapore"],
    verified: true,
    completedCampaigns: 68,
    averageRating: 4.8,
    joinedDate: "2024-03-20",
  },
  {
    id: "cr-003",
    handle: "@priya.fitness",
    displayName: "Priya Kaur",
    avatarUrl: "",
    bio: "Certified personal trainer. Helping you find strength in body & mind. Based in SG. Content in EN/Hindi.",
    city: "Singapore",
    languages: ["English", "Hindi", "Punjabi"],
    categories: ["Fitness", "Wellness"],
    platforms: [
      { platform: "instagram", handle: "@priya.fitness", followers: 95000, url: "https://instagram.com/priya.fitness" },
      { platform: "youtube", handle: "Priya Fitness", followers: 32000, url: "https://youtube.com/@priyafitness" },
    ],
    rateCardSGD: {
      instagramPost: 600,
      instagramReel: 900,
      instagramStory: 250,
      youtubeVideo: 2500,
    },
    tags: ["Fitness", "Workout", "Wellness", "Healthy"],
    verified: true,
    completedCampaigns: 28,
    averageRating: 4.9,
    joinedDate: "2024-11-02",
  },
  {
    id: "cr-004",
    handle: "@aisyah.styles",
    displayName: "Aisyah Rahman",
    avatarUrl: "",
    bio: "Modest fashion + halal lifestyle in SG. Sharing outfits, travel, and everyday life. EN/Malay.",
    city: "Singapore",
    languages: ["English", "Malay"],
    categories: ["Fashion", "Lifestyle", "Travel"],
    platforms: [
      { platform: "instagram", handle: "@aisyah.styles", followers: 210000, url: "https://instagram.com/aisyah.styles" },
      { platform: "tiktok", handle: "@aisyah.styles", followers: 340000, url: "https://tiktok.com/@aisyah.styles" },
    ],
    rateCardSGD: {
      instagramPost: 1500,
      instagramReel: 2200,
      instagramStory: 400,
      tiktokVideo: 2000,
    },
    tags: ["Fashion", "Modest", "Halal", "Travel"],
    verified: true,
    completedCampaigns: 85,
    averageRating: 5.0,
    joinedDate: "2023-12-10",
  },
  {
    id: "cr-005",
    handle: "@daniel.techreviews",
    displayName: "Daniel Lim",
    avatarUrl: "",
    bio: "Tech reviewer. Phones, laptops, gadgets — honest reviews from a Singapore consumer's POV.",
    city: "Singapore",
    languages: ["English", "Mandarin"],
    categories: ["Tech", "Gadgets"],
    platforms: [
      { platform: "youtube", handle: "Daniel Tech", followers: 380000, url: "https://youtube.com/@danieltech" },
      { platform: "instagram", handle: "@daniel.techreviews", followers: 75000, url: "https://instagram.com/daniel.techreviews" },
      { platform: "tiktok", handle: "@daniel.tech", followers: 125000, url: "https://tiktok.com/@daniel.tech" },
    ],
    rateCardSGD: {
      instagramPost: 700,
      instagramReel: 1100,
      tiktokVideo: 1300,
      youtubeVideo: 5000,
      youtubeShort: 1500,
    },
    tags: ["Tech", "Reviews", "Gadgets", "Phones"],
    verified: true,
    completedCampaigns: 54,
    averageRating: 4.7,
    joinedDate: "2024-05-18",
  },
  {
    id: "cr-006",
    handle: "@littlemay.family",
    displayName: "May Koh",
    avatarUrl: "",
    bio: "Mum of 2 sharing parenting tips, kids' products, and family activities in SG. Trusted by 130k+ parents.",
    city: "Singapore",
    languages: ["English", "Mandarin"],
    categories: ["Parenting", "Lifestyle", "F&B"],
    platforms: [
      { platform: "instagram", handle: "@littlemay.family", followers: 130000, url: "https://instagram.com/littlemay.family" },
      { platform: "tiktok", handle: "@littlemay.family", followers: 95000, url: "https://tiktok.com/@littlemay.family" },
    ],
    rateCardSGD: {
      instagramPost: 900,
      instagramReel: 1400,
      instagramStory: 300,
      tiktokVideo: 1200,
    },
    tags: ["Parenting", "Family", "Kids", "Lifestyle"],
    verified: true,
    completedCampaigns: 37,
    averageRating: 4.9,
    joinedDate: "2024-06-01",
  },
  {
    id: "cr-007",
    handle: "@ryo.travels",
    displayName: "Ryo Nakamura",
    avatarUrl: "",
    bio: "Expat in SG sharing travel guides across SEA. Japan x Singapore lifestyle. Content in EN/Japanese.",
    city: "Singapore",
    languages: ["English", "Japanese"],
    categories: ["Travel", "Lifestyle", "F&B"],
    platforms: [
      { platform: "instagram", handle: "@ryo.travels", followers: 88000, url: "https://instagram.com/ryo.travels" },
      { platform: "youtube", handle: "Ryo in SG", followers: 52000, url: "https://youtube.com/@ryoinsg" },
    ],
    rateCardSGD: {
      instagramPost: 600,
      instagramReel: 900,
      youtubeVideo: 2800,
    },
    tags: ["Travel", "SEA", "Expat", "Japanese"],
    verified: false,
    completedCampaigns: 15,
    averageRating: 4.8,
    joinedDate: "2025-01-20",
  },
  {
    id: "cr-008",
    handle: "@jasmine.home",
    displayName: "Jasmine Wong",
    avatarUrl: "",
    bio: "HDB & condo interior inspiration. Home decor finds, IKEA hacks, DIY projects. Real homes, real budgets.",
    city: "Singapore",
    languages: ["English"],
    categories: ["Home", "Lifestyle"],
    platforms: [
      { platform: "instagram", handle: "@jasmine.home", followers: 155000, url: "https://instagram.com/jasmine.home" },
      { platform: "tiktok", handle: "@jasmine.home", followers: 210000, url: "https://tiktok.com/@jasmine.home" },
      { platform: "xiaohongshu", handle: "jasmine.home", followers: 45000, url: "https://xiaohongshu.com/user/jasmine.home" },
    ],
    rateCardSGD: {
      instagramPost: 1000,
      instagramReel: 1500,
      tiktokVideo: 1400,
    },
    tags: ["Home", "Interior", "HDB", "Decor"],
    verified: true,
    completedCampaigns: 48,
    averageRating: 4.9,
    joinedDate: "2024-04-12",
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp-001",
    brandId: "br-001",
    brandName: "Glow Skincare Co.",
    title: "New Vitamin C Serum Launch",
    description:
      "Launching our new Vitamin C Brightening Serum. Looking for beauty creators to share authentic reviews.",
    briefMarkdown:
      "We're launching our flagship Vitamin C Serum and need authentic reviews from beauty creators in Singapore.\n\n**What we're looking for:**\n- 7-day usage video/reel\n- Before/after comparison\n- Honest review of texture, absorption, and results\n- English or Mandarin content",
    productName: "Glow Vitamin C Brightening Serum",
    deliverables: [
      { type: "instagram_reel", quantity: 1, requirements: "60-90 second reel showing product use" },
      { type: "instagram_story", quantity: 3, requirements: "Stories across the 7-day trial" },
    ],
    budgetSGD: 15000,
    paymentPerCreatorSGD: 1500,
    status: "open",
    categories: ["Beauty", "Skincare"],
    platforms: ["instagram", "tiktok"],
    targetCity: "Singapore",
    minFollowers: 50000,
    maxFollowers: 500000,
    applicationDeadline: "2026-04-25",
    contentDeadline: "2026-05-15",
    startDate: "2026-04-15",
    endDate: "2026-05-31",
    createdAt: "2026-04-10",
    applicants: [
      {
        id: "app-001",
        campaignId: "camp-001",
        creatorId: "cr-001",
        creatorHandle: "@shermaine.sg",
        message: "I'd love to try this! Vitamin C is one of my favourite ingredients.",
        proposedRate: 1500,
        status: "shortlisted",
        appliedAt: "2026-04-12",
      },
    ],
    selectedCreators: [],
  },
  {
    id: "camp-002",
    brandId: "br-001",
    brandName: "Hawker Heritage",
    title: "Hawker Culture Heritage Campaign",
    description:
      "Celebrating Singapore's hawker culture. Looking for food creators to highlight traditional hawker stalls.",
    briefMarkdown:
      "As part of our Heritage Month campaign, we want to spotlight 5 traditional hawker stalls across Singapore.\n\n**Requirements:**\n- Visit 1-2 stalls from our partner list\n- 2-3 minute TikTok or YouTube Short\n- Focus on the story of the stall owner\n- Must include our campaign hashtag #HawkerHeritageSG",
    productName: "Hawker Heritage Month Campaign",
    deliverables: [
      { type: "tiktok_video", quantity: 1, requirements: "2-3 minute TikTok telling stall owner's story" },
      { type: "instagram_story", quantity: 3, requirements: "Behind the scenes stories" },
    ],
    budgetSGD: 25000,
    paymentPerCreatorSGD: 2500,
    status: "open",
    categories: ["F&B"],
    platforms: ["tiktok", "instagram"],
    targetCity: "Singapore",
    minFollowers: 30000,
    maxFollowers: 1000000,
    applicationDeadline: "2026-04-30",
    contentDeadline: "2026-05-30",
    startDate: "2026-04-20",
    endDate: "2026-06-15",
    createdAt: "2026-04-08",
    applicants: [
      {
        id: "app-002",
        campaignId: "camp-002",
        creatorId: "cr-002",
        creatorHandle: "@marcustan_eats",
        message: "This is exactly what I love documenting. Count me in!",
        proposedRate: 2500,
        status: "accepted",
        appliedAt: "2026-04-09",
      },
    ],
    selectedCreators: ["cr-002"],
  },
  {
    id: "camp-003",
    brandId: "br-002",
    brandName: "TechWave SG",
    title: "New Smartphone Launch Review",
    description:
      "Honest reviews for our new flagship smartphone. Tech creators only.",
    briefMarkdown:
      "We're launching our flagship phone in Singapore and want honest, in-depth reviews from tech creators.\n\n**Deliverables:**\n- 10+ minute YouTube review\n- Full camera comparison\n- Gaming performance test\n- Battery life real-world test",
    productName: "TechWave Pro 15",
    deliverables: [
      { type: "youtube_video", quantity: 1, requirements: "10+ minute in-depth review" },
      { type: "youtube_short", quantity: 2, requirements: "Highlight features in YouTube Shorts" },
    ],
    budgetSGD: 20000,
    paymentPerCreatorSGD: 5000,
    status: "in_progress",
    categories: ["Tech", "Gadgets"],
    platforms: ["youtube"],
    targetCity: "Singapore",
    minFollowers: 100000,
    maxFollowers: 1000000,
    applicationDeadline: "2026-04-10",
    contentDeadline: "2026-05-01",
    startDate: "2026-04-05",
    endDate: "2026-05-15",
    createdAt: "2026-03-28",
    applicants: [
      {
        id: "app-003",
        campaignId: "camp-003",
        creatorId: "cr-005",
        creatorHandle: "@daniel.techreviews",
        message: "Excited to test this out. My usual review format works well here.",
        proposedRate: 5000,
        status: "accepted",
        appliedAt: "2026-04-02",
      },
    ],
    selectedCreators: ["cr-005"],
  },
  {
    id: "camp-004",
    brandId: "br-003",
    brandName: "FitPro Supplements",
    title: "Protein Powder Fitness Challenge",
    description: "30-day fitness challenge with our new whey protein. Looking for fitness creators.",
    briefMarkdown: "Join our 30-day fitness challenge.\n\n- Daily workout stories\n- Before/after photos\n- Recipe ideas using our protein",
    productName: "FitPro Whey Isolate",
    deliverables: [
      { type: "instagram_reel", quantity: 2, requirements: "Workout reels featuring product" },
      { type: "instagram_story", quantity: 10, requirements: "Daily stories during challenge" },
    ],
    budgetSGD: 8000,
    paymentPerCreatorSGD: 800,
    status: "draft",
    categories: ["Fitness", "Wellness"],
    platforms: ["instagram"],
    targetCity: "Singapore",
    minFollowers: 20000,
    maxFollowers: 300000,
    applicationDeadline: "2026-05-10",
    contentDeadline: "2026-06-15",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    createdAt: "2026-04-05",
    applicants: [],
    selectedCreators: [],
  },
  {
    id: "camp-005",
    brandId: "br-001",
    brandName: "HomeStyle SG",
    title: "HDB Home Makeover Series",
    description: "Budget-friendly HDB home makeovers featuring our furniture collection.",
    briefMarkdown: "Show how our furniture transforms a small HDB space. Focus on affordability and style.",
    productName: "HomeStyle Compact Collection",
    deliverables: [
      { type: "instagram_reel", quantity: 1, requirements: "Before/after makeover reel" },
      { type: "tiktok_video", quantity: 1, requirements: "Room tour TikTok" },
    ],
    budgetSGD: 12000,
    paymentPerCreatorSGD: 2000,
    status: "completed",
    categories: ["Home", "Lifestyle"],
    platforms: ["instagram", "tiktok"],
    targetCity: "Singapore",
    minFollowers: 50000,
    maxFollowers: 500000,
    applicationDeadline: "2026-02-15",
    contentDeadline: "2026-03-15",
    startDate: "2026-02-01",
    endDate: "2026-03-31",
    createdAt: "2026-01-25",
    applicants: [],
    selectedCreators: ["cr-008"],
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "plan-free",
    name: "Starter",
    priceSGD: 0,
    period: "month",
    description: "Perfect for trying out the platform",
    features: [
      "Browse up to 20 creator profiles/month",
      "1 active campaign",
      "Basic messaging",
      "Email support",
    ],
  },
  {
    id: "plan-growth",
    name: "Growth",
    priceSGD: 299,
    period: "month",
    description: "For small brands scaling their influencer marketing",
    features: [
      "Unlimited creator browsing",
      "5 active campaigns",
      "Advanced filters",
      "Campaign templates",
      "Priority messaging",
      "Chat support",
    ],
  },
  {
    id: "plan-pro",
    name: "Pro",
    priceSGD: 799,
    period: "month",
    description: "For established brands with ongoing campaigns",
    features: [
      "Unlimited creator browsing",
      "Unlimited campaigns",
      "Saved creator lists",
      "Team collaboration (up to 5 users)",
      "Custom campaign briefs",
      "Dedicated account manager",
      "Contract templates",
    ],
    recommended: true,
  },
  {
    id: "plan-enterprise",
    name: "Enterprise",
    priceSGD: -1,
    period: "month",
    description: "Custom solutions for agencies & large brands",
    features: [
      "Everything in Pro",
      "Unlimited team members",
      "White-label options",
      "Custom integrations",
      "SLA guarantee",
      "Invoice billing",
      "Quarterly strategy calls",
    ],
  },
];
