import { Affiliate, Campaign, PricingPlan } from "./types";

export const mockAffiliates: Affiliate[] = [
  {
    id: "af-001",
    userId: "u-001",
    tiktokHandle: "@beauty_mika",
    tiktokUrl: "https://tiktok.com/@beauty_mika",
    followers: 520000,
    avgViews: 180000,
    engagementRate: 8.5,
    categories: ["美容", "コスメ", "スキンケア"],
    region: "東京",
    bio: "現役美容部員。プチプラからデパコスまで幅広くレビュー。TikTok Shop売上月間TOP10入り。",
    avatarUrl: "",
    monthlyGmv: 3200000,
    affiliateScore: 95,
    verifiedAt: "2025-06-01",
    recentVideos: [
      {
        id: "v-001",
        thumbnailUrl: "",
        title: "【神コスメ】1000円以下で見つけた最強ファンデ",
        views: 450000,
        likes: 32000,
        comments: 1800,
        shares: 5600,
        postedAt: "2026-03-28",
      },
      {
        id: "v-002",
        thumbnailUrl: "",
        title: "朝のスキンケアルーティン全公開",
        views: 280000,
        likes: 21000,
        comments: 950,
        shares: 3200,
        postedAt: "2026-03-25",
      },
    ],
    stats: {
      totalSales: 8500,
      totalRevenue: 12800000,
      conversionRate: 4.2,
      avgOrderValue: 3500,
      monthlyGrowth: 12.5,
    },
  },
  {
    id: "af-002",
    userId: "u-002",
    tiktokHandle: "@gadget_taro",
    tiktokUrl: "https://tiktok.com/@gadget_taro",
    followers: 380000,
    avgViews: 150000,
    engagementRate: 7.2,
    categories: ["ガジェット", "テック", "レビュー"],
    region: "大阪",
    bio: "元家電量販店スタッフ。ガジェット・家電のリアルレビュー。Amazonアフィリエイト歴5年。",
    avatarUrl: "",
    monthlyGmv: 2800000,
    affiliateScore: 88,
    verifiedAt: "2025-07-15",
    recentVideos: [
      {
        id: "v-003",
        thumbnailUrl: "",
        title: "Amazonで買える神ガジェットTOP5",
        views: 320000,
        likes: 25000,
        comments: 1200,
        shares: 4100,
        postedAt: "2026-03-30",
      },
    ],
    stats: {
      totalSales: 5200,
      totalRevenue: 8500000,
      conversionRate: 3.8,
      avgOrderValue: 4800,
      monthlyGrowth: 8.3,
    },
  },
  {
    id: "af-003",
    userId: "u-003",
    tiktokHandle: "@fit_yuna",
    tiktokUrl: "https://tiktok.com/@fit_yuna",
    followers: 290000,
    avgViews: 120000,
    engagementRate: 9.1,
    categories: ["フィットネス", "健康", "サプリ"],
    region: "福岡",
    bio: "パーソナルトレーナー。ダイエット・筋トレのリアルな情報発信。プロテイン・サプリのレビューも。",
    avatarUrl: "",
    monthlyGmv: 1800000,
    affiliateScore: 82,
    verifiedAt: "2025-09-01",
    recentVideos: [
      {
        id: "v-004",
        thumbnailUrl: "",
        title: "ダイエット中でもOK！高タンパクおやつ5選",
        views: 210000,
        likes: 18000,
        comments: 800,
        shares: 2900,
        postedAt: "2026-03-29",
      },
    ],
    stats: {
      totalSales: 3800,
      totalRevenue: 5700000,
      conversionRate: 5.1,
      avgOrderValue: 2800,
      monthlyGrowth: 15.2,
    },
  },
  {
    id: "af-004",
    userId: "u-004",
    tiktokHandle: "@fashion_remi",
    tiktokUrl: "https://tiktok.com/@fashion_remi",
    followers: 680000,
    avgViews: 250000,
    engagementRate: 6.8,
    categories: ["ファッション", "アパレル", "韓国ファッション"],
    region: "東京",
    bio: "韓国ファッション大好き！プチプラで高見えするコーデを毎日紹介。SHEIN・Qoo10の達人。",
    avatarUrl: "",
    monthlyGmv: 4500000,
    affiliateScore: 91,
    verifiedAt: "2025-05-20",
    recentVideos: [
      {
        id: "v-005",
        thumbnailUrl: "",
        title: "SHEIN購入品開封！全部3000円以下",
        views: 520000,
        likes: 38000,
        comments: 2100,
        shares: 6800,
        postedAt: "2026-03-31",
      },
    ],
    stats: {
      totalSales: 12000,
      totalRevenue: 18000000,
      conversionRate: 3.5,
      avgOrderValue: 2200,
      monthlyGrowth: 10.1,
    },
  },
  {
    id: "af-005",
    userId: "u-005",
    tiktokHandle: "@cooking_papa",
    tiktokUrl: "https://tiktok.com/@cooking_papa",
    followers: 420000,
    avgViews: 200000,
    engagementRate: 7.8,
    categories: ["料理", "キッチン", "食品"],
    region: "名古屋",
    bio: "2児のパパ。簡単・時短レシピと便利キッチングッズの紹介。調理家電のレビューが得意。",
    avatarUrl: "",
    monthlyGmv: 2100000,
    affiliateScore: 85,
    verifiedAt: "2025-08-10",
    recentVideos: [
      {
        id: "v-006",
        thumbnailUrl: "",
        title: "10分で完成！子どもが喜ぶ簡単おかず",
        views: 350000,
        likes: 28000,
        comments: 1500,
        shares: 4500,
        postedAt: "2026-03-27",
      },
    ],
    stats: {
      totalSales: 6200,
      totalRevenue: 9300000,
      conversionRate: 4.5,
      avgOrderValue: 3100,
      monthlyGrowth: 9.8,
    },
  },
  {
    id: "af-006",
    userId: "u-006",
    tiktokHandle: "@pet_hana",
    tiktokUrl: "https://tiktok.com/@pet_hana",
    followers: 310000,
    avgViews: 160000,
    engagementRate: 10.2,
    categories: ["ペット", "犬", "ペット用品"],
    region: "札幌",
    bio: "トイプードル2匹と暮らす愛犬家。ペットグッズの本音レビュー。動物看護師の資格持ち。",
    avatarUrl: "",
    monthlyGmv: 1500000,
    affiliateScore: 79,
    verifiedAt: "2025-10-05",
    recentVideos: [
      {
        id: "v-007",
        thumbnailUrl: "",
        title: "愛犬が大喜び！最新おもちゃレビュー",
        views: 280000,
        likes: 30000,
        comments: 2000,
        shares: 3800,
        postedAt: "2026-03-26",
      },
    ],
    stats: {
      totalSales: 2900,
      totalRevenue: 4350000,
      conversionRate: 5.8,
      avgOrderValue: 2500,
      monthlyGrowth: 18.5,
    },
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "c-001",
    advertiserId: "adv-001",
    title: "新作リップティント プロモーション",
    description:
      "春の新作リップティントのTikTokアフィリエイトプロモーション。使用感やBefore/Afterの動画を投稿してください。",
    productName: "グロウリップティント #春色コレクション",
    productUrl: "https://example.com/product/lip-tint",
    productImageUrl: "",
    commissionRate: 15,
    commissionType: "percentage",
    budget: 500000,
    spent: 185000,
    status: "active",
    categories: ["美容", "コスメ"],
    targetRegion: "全国",
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    applicants: [
      {
        id: "app-001",
        campaignId: "c-001",
        affiliateId: "af-001",
        status: "approved",
        message: "美容系コンテンツをメインで発信しています。ぜひ協力させてください！",
        appliedAt: "2026-03-28",
      },
      {
        id: "app-002",
        campaignId: "c-001",
        affiliateId: "af-004",
        status: "pending",
        message: "ファッション・美容の複合コンテンツで訴求できます。",
        appliedAt: "2026-03-30",
      },
    ],
    createdAt: "2026-03-25",
  },
  {
    id: "c-002",
    advertiserId: "adv-001",
    title: "ワイヤレスイヤホン レビューキャンペーン",
    description:
      "最新ワイヤレスイヤホンのレビュー動画を投稿してください。音質比較や使用シーンの紹介を希望。",
    productName: "ProSound X1 ワイヤレスイヤホン",
    productUrl: "https://example.com/product/earbuds",
    productImageUrl: "",
    commissionRate: 2000,
    commissionType: "fixed",
    budget: 300000,
    spent: 48000,
    status: "active",
    categories: ["ガジェット", "テック"],
    targetRegion: "全国",
    startDate: "2026-04-01",
    endDate: "2026-05-15",
    applicants: [
      {
        id: "app-003",
        campaignId: "c-002",
        affiliateId: "af-002",
        status: "approved",
        message: "ガジェットレビューが得意です！",
        appliedAt: "2026-03-29",
      },
    ],
    createdAt: "2026-03-26",
  },
  {
    id: "c-003",
    advertiserId: "adv-001",
    title: "オーガニックプロテイン 体験レビュー",
    description:
      "オーガニックプロテインの味・飲みやすさ・効果をレビューしてください。トレーニング動画との組み合わせ歓迎。",
    productName: "NatureFit オーガニックホエイプロテイン",
    productUrl: "https://example.com/product/protein",
    productImageUrl: "",
    commissionRate: 20,
    commissionType: "percentage",
    budget: 200000,
    spent: 0,
    status: "draft",
    categories: ["フィットネス", "健康", "サプリ"],
    targetRegion: "全国",
    startDate: "2026-04-15",
    endDate: "2026-05-31",
    applicants: [],
    createdAt: "2026-04-01",
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "plan-free",
    name: "フリー",
    price: 0,
    period: "月",
    description: "まずはお試しで始めたい企業様向け",
    features: [
      "アフィリエイター検索（月10件まで）",
      "キャンペーン作成（1件まで）",
      "基本レポート",
      "メールサポート",
    ],
    maxCampaigns: 1,
    maxAffiliates: 10,
  },
  {
    id: "plan-starter",
    name: "スターター",
    price: 29800,
    period: "月",
    description: "本格的にTikTokアフィリエイトを始める企業様向け",
    features: [
      "アフィリエイター検索（無制限）",
      "キャンペーン作成（5件まで）",
      "詳細レポート＆分析",
      "アフィリエイタースコア閲覧",
      "チャットサポート",
      "CSV エクスポート",
    ],
    maxCampaigns: 5,
    maxAffiliates: 100,
  },
  {
    id: "plan-pro",
    name: "プロ",
    price: 79800,
    period: "月",
    description: "大規模にアフィリエイト施策を展開したい企業様向け",
    features: [
      "アフィリエイター検索（無制限）",
      "キャンペーン作成（無制限）",
      "リアルタイムダッシュボード",
      "AIマッチング機能",
      "専属カスタマーサクセス",
      "API連携",
      "カスタムレポート",
      "優先サポート",
    ],
    recommended: true,
    maxCampaigns: -1,
    maxAffiliates: -1,
  },
  {
    id: "plan-enterprise",
    name: "エンタープライズ",
    price: -1,
    period: "月",
    description: "カスタマイズが必要な大企業様向け",
    features: [
      "プロプランの全機能",
      "専用環境構築",
      "SLA保証",
      "カスタムAPI開発",
      "オンボーディング支援",
      "月次戦略ミーティング",
      "複数ブランド管理",
      "請求書払い対応",
    ],
    maxCampaigns: -1,
    maxAffiliates: -1,
  },
];
